name: Dev Django CI

on:
  push:
    branches: [ "dev-server" ]
  pull_request:
    branches: [ "dev-server" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3


    - name: Configure SSH key
      uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.DEV_SSH_PRIVATE_KEY }}

    - name: Deploy
      env:
        REMOTE_IP: ${{ secrets.DEV_REMOTE_IP }}
        PROJECT_PATH: ${{ secrets.PROJECT_PATH }}
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@$REMOTE_IP "cd $PROJECT_PATH && docker-compose up --build -d"